### ISSUE TITLE
Could you provide other shell supports like zsh?

### ISSUE THREAD

**Issue by ghost** [qparis/FinderOpenTerminal#1]
Hi, I like your app, it is good-looking and convenient. But I think it can be better if you would provide other shell supports, like zsh. I am a zsh user, and I want to open my terminal with it but not bash. I have already found that

``` shell
"exec bash -c \"clear;printf '\\e[3J';bash --rcfile $rcFile\""
```

in AppDelegate.swift should be modified, but when I want to change the code myself, Xcode warn me
"**Failed to code sign "Open Terminal Finder Extension".**
No non–expired provisioning profiles were found.

Xcode can attempt to fix this issue. This will reset your code signing and provisioning settings to recommended values and resolve issues with signing identities and provisioning profiles."
I don't know what to do next though I searched on Internet. Can you please add this feature? I think code like

``` shell
echo ${SHELL}
```

will help to judge what shell to use.
Thank you!

**Comment by qparis** [comment]
The main problem is that the option --rcfile is not supported for zsh. We need to write specific code to support it

**Comment by ghost** [comment]
OK, I am looking forward to it. Thank you!

**Comment by qparis** [comment]
Should be fixed
