### ISSUE TITLE
Problems uninstalling

### ISSUE THREAD

**Issue by alank14** [qparis/FinderOpenTerminal#10]
When I try to just delete OpenTerminal.app, I get: "The item “Open Terminal.app” can’t be moved to the Trash because some of its extensions are in use."

Indeed, I see how the app created an "Open Terminal" option in the contextual menu for any given folder, within the Finder. (For me, it's the fourth one down, called "Open Terminal").

I'm unable to locate that service within System Preferences or elsewhere, to remove it.

I've also searched manually within:
	/Library/Contextual Menu Items/
	/Library/Services/
	/Users/alan/Library/Services/

Many thanks,
Alan.

**Comment by hishamkaram** [comment]
open activity monitor and kill process Open Terminal Extension Process

**Comment by qparis** [comment]
This issue seems to be fixed. Feel free to reopen one if needed
