### ISSUE TITLE
Failed to execute process '/tmp/openTerminal'

### ISSUE THREAD

**Issue by hutger** [qparis/FinderOpenTerminal#4]
Hi, 

Whenever I try to run OpenTerminal, I got the error message below:

user@MacBook-Pro ~> /tmp/openTerminal ; exit;
Failed to execute process '/tmp/openTerminal'. Reason:
exec: Exec format error
The file '/tmp/openTerminal' is marked as an executable but could not be run by the operating system.
[Process completed]

Have you seen this error?

By the way, I'm using OS X El captain

Thanks

**Comment by qparis** [comment]
Should be fixed now
