### ISSUE TITLE
Open Terminal option doesn't work in Mac Os Sierra

### ISSUE THREAD

**Issue by Jefreesujit** [qparis/FinderOpenTerminal#5]
When i tried to right click -> Open Terminal. No terminal is opened. There is no exception message too. The screen appears as such.

**Comment by qparis** [comment]
It appears to be working on my laptop.
Have you tried to uninstall / reinstall it properly?

**Comment by Jefreesujit** [comment]
yeah, i tried.. still it doesn't work for me. I could see the Open terminal option in right click, but it doesn't have any action. Does you app work for Mac OS Sierra ie., macOS 10.12?

**Comment by rajivseelam** [comment]
Hi,

Doesn't work on macOS 10.12, May be you could check. Thanks.

**Comment by liufsd** [comment]
Doesn't work on macOS 10.12
The file /Users/liupeng/Library/Containers/fr.qparis.openterminal.Open-Terminal-Finder-Extension/Data/terminal:/Users/liupeng/Desktop does not exist.
