### ISSUE TITLE
Opening directories containing spaces are not working  

### ISSUE THREAD

**Issue by B-Lach** [qparis/FinderOpenTerminal#7]
Failed hard, sorry for that: `URL.path` will replace `"%20"` with `" "` but the constructor of `URL(string:)` is  assuming the string contains `"%20"` -> An instance of of URL(string:) will always fail if the path contains space

**Comment by qparis** [comment]
All right, I've had fixed this before, but forgot to commit. 
The version I have uploaded online is working.
Thanks :)

**Comment by B-Lach** [comment]
Good to know you've already fixed that. Sorry again.
